name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # Thursday 5.53pm UTC, which is Friday 5.53am NZST
    - cron: '53 17 * * 4'
    # Thursday 4.53pm UTC, which is Friday 5.53am NZDT
    # - cron: '53 16 * * 4'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: squash
          automerge_fail_label: 'merge-schedule-failed'
        env:
          GITHUB_TOKEN: ${{ secrets.SCHEDULED_MERGE_TOKEN }}
